name: Staging CI
on:
  push:
    branches: [release]
jobs:
  staging-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # changes v3 ko v4 kar diya

      - name: Docker Build
        run: docker build -t cs-site-staging .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  
        with:
          name: production-files
          path: .